name: cmake --build
on:
  push:
    branches: ["main"]
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/cmake-build.yml"
  pull_request:
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/cmake-build.yml"
  workflow_call:
concurrency:
  # When run via `workflow_call` the `github.workflow` and `github.ref` are the
  # same as the parent so we need a differentiation suffix.
  group: ${{ github.workflow }}-${{ github.ref }}-cmake-build
  cancel-in-progress: true
jobs:
  cmake-build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - x86_64-unknown-macos-none
          - aarch64-unknown-macos-none
          # - x86_64-unknown-windows-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: goto-bus-stop/setup-zig@v2
      - uses: jwlawson/actions-setup-cmake@v2
      - shell: bash
        run: ./task.cmake build "$TARGET"
        env:
          TARGET: ${{ matrix.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: quickjs-${{ matrix.target }}
          path: |
            quickjs/build/**/libqjs.a
            quickjs/build/**/qjs.lib
  cmake-build-x86_64-pc-windows-msvc:
    runs-on: windows-latest
    env:
      target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: jwlawson/actions-setup-cmake@v2
      - shell: bash
        run: ./task.cmake build "$TARGET"
        env:
          TARGET: ${{ env.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: quickjs-${{ env.target }}
          path: quickjs/build/**/qjs.lib